package(default_visibility = ["//visibility:public"])

filegroup(
    name = "birdcage_head_data",
    srcs = glob(
        ["birdcage_head_*.fld"],
        exclude = ["birdcage_head_sar.fld"],
    ),
)

filegroup(
    name = "birdcage_head_mask",
    srcs = ["birdcage_head_sar.fld"],
)

filegroup(
    name = "birdcage_phantom_data",
    srcs = glob(
        ["birdcage_phantom_*.fld"],
        exclude = ["birdcage_phantom_sar.fld"],
    ),
)

filegroup(
    name = "birdcage_phantom_mask",
    srcs = ["birdcage_phantom_sar.fld"],
)

filegroup(
    name = "parallel_tx_phantom_b1_maps",
    srcs = glob(["parallel_tx_phantom_b1_map_*.fld"]),
)

filegroup(
    name = "parallel_tx_phantom_b1_mask",
    srcs = ["parallel_tx_phantom_sar.fld"],
)

filegroup(
    name = "parallel_tx_phantom_data",
    srcs = ["parallel_tx_phantom_7T_shimmed.fld"],
)

filegroup(
    name = "parallel_tx_phantom_shims",
    srcs = ["parallel_tx_phantom_shims.csv"],
)

filegroup(
    name = "all_data",
    srcs = [
        ":birdcage_head_data",
        ":birdcage_phantom_data",
        ":parallel_tx_phantom_data",
    ],
)

filegroup(
    name = "all_b1_maps",
    srcs = [":parallel_tx_phantom_b1_maps"],
)

filegroup(
    name = "all_masks",
    srcs = [
        ":birdcage_head_mask",
        ":birdcage_phantom_mask",
        ":parallel_tx_phantom_b1_mask",
    ],
)

filegroup(
    name = "all_shims",
    srcs = [":parallel_tx_phantom_shims"],
)
